[project]
name = "twitch-recorder"
version = "0.1.0"
description = "A simple tool to record Twitch live streams."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlink>=7.6.0",
]